# Generated by Django 5.1.1 on 2024-11-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_options_alter_customer_table_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
