# Generated by Django 5.1.1 on 2024-11-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_quntity_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='restaurent',
            new_name='store',
        ),
    ]
