# Generated by Django 5.1.1 on 2024-11-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_restaurent_cart_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=200)),
                ('appartement', models.CharField(max_length=200)),
                ('landmark', models.IntegerField(max_length=200)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'verbose_name': 'bill',
                'verbose_name_plural': 'bills',
                'db_table': 'bill',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemtotal', models.CharField(max_length=225)),
                ('offerapplied', models.CharField(max_length=225)),
                ('deliverycharges', models.CharField(max_length=225)),
                ('final_amount', models.FloatField()),
                ('address', models.ForeignKey(max_length=225, on_delete=django.db.models.deletion.CASCADE, to='customer.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'verbose_name': 'bill',
                'verbose_name_plural': 'bills',
                'db_table': 'customer_bill',
                'ordering': ['-id'],
            },
        ),
    ]
