# Generated by Django 5.1.1 on 2024-11-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_address_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='landmark',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
