# Generated by Django 5.1.1 on 2024-11-11 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.address'),
        ),
    ]
