# Generated by Django 5.1.1 on 2024-11-01 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.store')),
            ],
            options={
                'verbose_name': 'Foodcategory',
                'verbose_name_plural': 'Foodcategories',
                'db_table': 'Foodcategory',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('is_veg', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.store')),
                ('Foodcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.foodcategory')),
            ],
            options={
                'verbose_name': 'food',
                'verbose_name_plural': 'foods',
                'db_table': 'store_food',
                'ordering': ['-id'],
            },
        ),
    ]
