# Generated by Django 5.0.6 on 2024-11-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_foodcategory_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='short_discription',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
